# Generated by Django 5.1.1 on 2024-11-26 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_barrier_multiple_risk_associations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_barriers', to='core.barriercategory'),
        ),
    ]
